version: 2

volumes:
  bajie-redis-data:
    driver: local

services:
  cache:
    image: redis:3.2-alpine
    container_name: bajie-redis
    command: --appendonly yes
    volumes:
      - bajie-redis-data:/data

  bajie:
    image: sejakino/bajie:latest
    container_name: bajie-web
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    links:
      - cache